"""Configuration file for the Sphinx documentation builder.

This file does only contain a selection of the most common options. For a full list see
the documentation: http://www.sphinx-doc.org/en/master/config

-- Path setup --------------------------------------------------------------

If extensions (or modules to document with autodoc) are in another directory, add these
directories to ``sys.path`` here. If the directory is relative to the documentation
root, use ``os.path.abspath`` to make it absolute, like shown here.
"""

import os
import sys
import zipfile
from calendar import month_name
from datetime import date
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version
from pathlib import Path

import pybtex.plugin
from pybtex.style.formatting.plain import Style as PlainStyle
from pybtex.style.formatting.unsrt import Style as UnsrtStyle
from pybtex.style.sorting import BaseSortingStyle

sys.path.insert(0, os.path.abspath("../../src"))
sys.path.insert(0, os.path.abspath("_ext"))

# -- Project information -----------------------------------------------------

project = "koopmans"
copyright = f"{date.today().year}, Edward Linscott"
author = "Edward Linscott"

# The full version, including any dev/local segment, read from the
# installed package's git-derived metadata (see [tool.hatch.version] in
# pyproject.toml).
try:
    release = _pkg_version("koopmans")
except PackageNotFoundError:
    release = "0.0.0+unknown"

# The short X.Y.Z version, with any dev/local segment stripped.
version = release.split(".dev")[0].split("+")[0]

if release != version:
    tags.add("prerelease")  # noqa:F821


# See https://about.readthedocs.com/blog/2024/07/addons-by-default/
# Define the canonical URL if you are using a custom domain on Read the Docs
html_baseurl = os.environ.get("READTHEDOCS_CANONICAL_URL", "")

# See https://about.readthedocs.com/blog/2024/07/addons-by-default/
# Tell Jinja2 templates the build is running on Read the Docs
if os.environ.get("READTHEDOCS", "") == "True":
    if "html_context" not in globals():
        html_context = {}
    html_context["READTHEDOCS"] = True

    # Warn readers of the published documentation that it is unfinished. Read
    # the Docs' own notifications carry fixed wording, so this one is ours,
    # prepended to every page. A local build shows the pages without it.
    rst_prolog = """
.. attention::

    These pages are under construction — come back soon!
"""


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = False

# A list of prefixes that are ignored when creating the module index. (new in Sphinx 0.6)
modindex_common_prefix = ["koopmans."]

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autosummary",
    "sphinx.ext.autodoc",
    "sphinx.ext.coverage",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx_automodapi.automodapi",
    "sphinx_automodapi.smart_resolver",
    "sphinxcontrib.autodoc_pydantic",
    "sphinx_design",
    "sphinx_copybutton",
    "sphinxcontrib.bibtex",
    "question",
    # 'texext',
]

bibtex_bibfiles = ["_static/references.bib"]
bibtex_default_style = "plainabbrev"


extensions.append("sphinx_click.ext")


# generate autosummary pages
autosummary_generate = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {
    ".rst": "restructuredtext",
}

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# ``logo_only`` drops the project name from under the sidebar logo, as the
# legacy documentation does.
html_theme_options = {"logo_only": True}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["custom.css"]

# Copy buttons on code blocks. A console block is copied without its `$ `
# prompts, and without the output lines that carry no prompt; a block with no
# prompt at all is copied whole.
copybutton_prompt_text = r"\$ "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "\\"

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar. The sidebar is dark, hence the white icon; the landing page
# uses the grey wordmark against the white page body.
html_logo = "_static/logo_icon.png"

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "koopmans_doc"

# -- Options for LaTeX output ------------------------------------------------

# latex_elements = {
#     The paper size ('letterpaper' or 'a4paper').
#
#     'papersize': 'letterpaper',
#
#     The font size ('10pt', '11pt' or '12pt').
#
#     'pointsize': '10pt',
#
#     Additional stuff for the LaTeX preamble.
#
#     'preamble': '',
#
#     Latex figure (float) alignment
#
#     'figure_align': 'htbp',
# }

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
# latex_documents = [
#     (
#         master_doc,
#         'koopmans.tex',
#         'koopmans Documentation',
#         author,
#         'manual',
#     ),
# ]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        master_doc,
        "koopmans",
        "koopmans Documentation",
        [author],
        1,
    ),
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "koopmans",
        "koopmans Documentation",
        author,
        "Edward Linscott",
        "Automated Koopmans functional calculations and workflows",
        "Miscellaneous",
    ),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
# epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
# epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
# Note: don't add trailing slashes, since sphinx adds "/objects.inv" to the end
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pandas": ("https://pandas.pydata.org/docs", None),
    "sklearn": ("https://scikit-learn.org/stable", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "scipy": ("https://docs.scipy.org/doc/scipy", None),
}

autoclass_content = "class"

# sphinxcontrib-autodoc-pydantic settings
autodoc_pydantic_model_show_config_summary = False
autodoc_pydantic_model_show_field_summary = False
autodoc_pydantic_model_show_validator_summary = False
autodoc_pydantic_model_show_validator_members = False
autodoc_pydantic_field_list_validators = False
autodoc_pydantic_model_show_json = False

# Don't sort alphabetically, explained at:
# https://stackoverflow.com/questions/37209921/python-how-not-to-sort-sphinx-output-in-alphabetical-order
autodoc_member_order = "bysource"

todo_include_todos = True
todo_emit_warnings = True

# Output SVG inheritance diagrams
graphviz_output_format = "svg"


# -- Bibliography styles ------------------------------------------------------


class ChronoSortingStyle(BaseSortingStyle):
    """Sort bibliography entries by date."""

    def sort(self, entries):
        """Return the entries oldest first."""

        def get_date(entry):
            month_lookup = list(month_name)
            year = int(entry.fields["year"])
            default_month = month_lookup[0]
            month = month_lookup.index(entry.fields.get("month", default_month))
            return date(year, month, 1)

        return sorted(entries, key=get_date)


class ChronoStyle(UnsrtStyle):
    """Format a bibliography in date order, with abbreviated author names."""

    def __init__(self, *args, **kwargs):
        """Sort by date and abbreviate author names."""
        kwargs.update(sorting_style=ChronoSortingStyle, abbreviate_names=True)
        super().__init__(*args, **kwargs)


class AbbrevPlainStyle(PlainStyle):
    """Format a bibliography alphabetically, with abbreviated author names."""

    def __init__(self, *args, **kwargs):
        """Abbreviate author names."""
        kwargs.update(abbreviate_names=True)
        super().__init__(*args, **kwargs)


pybtex.plugin.register_plugin("pybtex.style.formatting", "chrono", ChronoStyle)
pybtex.plugin.register_plugin("pybtex.style.formatting", "plainabbrev", AbbrevPlainStyle)


# -- Tutorial input archives --------------------------------------------------

# A tutorial that needs several input files in a particular layout ships them as
# one archive, built here from the files the tutorial itself includes, so that
# the archive and the page can never disagree. Each entry maps an archive to its
# members, both named relative to the directory holding the tutorial.
TUTORIAL_ARCHIVES = {
    "tutorials/orbital_energies/ozone/ozone_manually.zip": [
        "ozone_dft.in",
        "ozone_dft_n-1.in",
        "ozone_ki.in",
        "get_alpha.sh",
        "pseudopotentials/O_ONCV_PBE-1.2.upf",
    ],
}


def build_tutorial_archives(app):
    """Pack each tutorial's input files into the archive its page offers."""
    for archive, members in TUTORIAL_ARCHIVES.items():
        target = Path(app.srcdir) / archive
        with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as handle:
            for member in members:
                handle.write(target.parent / member, member)


def setup(app):
    """Register the documentation's own build steps."""
    app.connect("builder-inited", build_tutorial_archives)
