"""Generator for the input-file models of the calculators koopmans drives.

The generic models (``pydantic_espresso``, ``wannier90_input``) enumerate
every keyword their code accepts, including the ones a koopmans workflow
determines for itself. Those keywords are not koopmans input-file keywords
at all, so this rewrites each generic model as a restricted one that simply
does not declare them, and writes the result to
``koopmans/input_file/_generated/``.

Field declarations are copied verbatim from the generic model's own source,
so the restricted model carries the same types, defaults, descriptions and
per-field validators. Run it with ``just generate-input-models``; the
checked-in output is what koopmans imports.
"""

from __future__ import annotations

import ast
import inspect
from collections import defaultdict
from dataclasses import dataclass, field
from importlib import import_module
from pathlib import Path

from aiida_koopmans.owned_keywords import OWNED

__all__ = ["MODULES", "REASONS", "generate", "render"]

_HEADER = '''\
"""{summary}

Generated by ``koopmans.input_file._codegen`` from
{sources}.
Do not edit: run ``just generate-input-models`` instead.
"""

# ruff: noqa
'''


@dataclass(frozen=True)
class GeneratedModel:
    """One restricted model to emit.

    Args:
        source: Dotted path of the module declaring the generic model.
        name: Class name in ``source``.
        emitted: Name of the emitted class. It is the public name wherever
            koopmans has nothing to add to the restricted model, since a
            subclass that declares no field of its own documents as an empty
            model; where koopmans does add something, it takes an
            underscore-prefixed name and the public class subclasses it.
        block: Key into :data:`~aiida_koopmans.owned_keywords.OWNED` and
            :data:`REASONS`.
        path: Dotted path of the block in a koopmans input file, for the
            error message a removed keyword raises.
        summary: First line of the emitted class docstring.
    """

    source: str
    name: str
    emitted: str
    block: str
    path: str
    summary: str


@dataclass
class GeneratedModule:
    """One file to emit, holding one or more restricted models.

    Args:
        filename: File name under ``koopmans/input_file/_generated/``.
        summary: First line of the emitted module docstring.
        models: The models the file declares, in order.
    """

    filename: str
    summary: str
    models: list[GeneratedModel] = field(default_factory=list)


MODULES: list[GeneratedModule] = [
    GeneratedModule(
        "pw.py",
        "Restricted ``pw.x`` namelists.",
        [
            GeneratedModel(
                "pydantic_espresso.models.pw.develop",
                "ControlNamelist",
                "ControlNamelist",
                "pw.CONTROL",
                "calculator_parameters.pw.control",
                "``CONTROL`` namelist for ``pw.x`` calculations.",
            ),
            GeneratedModel(
                "pydantic_espresso.models.pw.develop",
                "SystemNamelist",
                "SystemNamelist",
                "pw.SYSTEM",
                "calculator_parameters.pw.system",
                "``SYSTEM`` namelist for ``pw.x`` calculations.",
            ),
        ],
    ),
    GeneratedModule(
        "ph.py",
        "Restricted ``ph.x`` namelist.",
        [
            GeneratedModel(
                "pydantic_espresso.models.ph.develop",
                "InputphNamelist",
                "_InputphNamelist",
                "ph.INPUTPH",
                "calculator_parameters.ph",
                "``INPUTPH`` namelist for ``ph.x``, less the keywords koopmans determines.",
            )
        ],
    ),
    GeneratedModule(
        "pw2wannier90.py",
        "Restricted ``pw2wannier90.x`` namelist.",
        [
            GeneratedModel(
                "pydantic_espresso.models.pw2wannier90.develop",
                "InputppNamelist",
                "PW2Wannier90InputParameters",
                "pw2wannier90.INPUTPP",
                "calculator_parameters.pw2wannier90",
                "Input parameters for ``pw2wannier90.x`` (the ``INPUTPP`` namelist).",
            )
        ],
    ),
    GeneratedModule(
        "wannier90.py",
        "Restricted ``wannier90.x`` input.",
        [
            GeneratedModel(
                "wannier90_input.models.latest",
                "Wannier90Input",
                "_Wannier90Input",
                "wannier90",
                "calculator_parameters.wannier90",
                "Input keywords for ``wannier90.x``, less the ones koopmans determines.",
            )
        ],
    ),
]

_AIIDA = "AiiDA writes it for every calculation it runs."
_SPIN = "Set `workflow.spin`."

#: Why each owned keyword is not a koopmans input-file keyword, and what to
#: set instead. Shown to whoever wrote the keyword, so it names input-file
#: fields rather than routes or plugins.
REASONS: dict[str, dict[str, str]] = {
    "pw.CONTROL": {
        "pseudo_dir": "Pseudopotentials come from `workflow.pseudo_library`.",
        "outdir": _AIIDA,
        "prefix": _AIIDA,
        "verbosity": "koopmans runs every pw.x calculation at high verbosity.",
    },
    "pw.SYSTEM": {
        "ibrav": "The lattice comes from the `cell_parameters` block.",
        "nat": "The atoms come from the `atomic_positions` block.",
        "ntyp": "The species come from the `atomic_positions` block.",
        "ecutwfc": (
            "Set `calculator_parameters.ecutwfc`: pw.x and kcp.x always share one grid, "
            "and `ecutrho` follows at four times it."
        ),
        "ecutrho": (
            "Set `calculator_parameters.ecutwfc`: pw.x and kcp.x always share one grid, "
            "and `ecutrho` follows at four times it."
        ),
        "nspin": _SPIN,
        "noncolin": _SPIN,
        "lspinorb": _SPIN,
    },
    "ph.INPUTPH": {
        "outdir": _AIIDA,
        "prefix": _AIIDA,
        "fildyn": _AIIDA,
        "verbosity": _AIIDA,
        "ldisp": "koopmans runs ph.x only at q = Gamma.",
        "nq1": "koopmans runs ph.x only at q = Gamma.",
        "nq2": "koopmans runs ph.x only at q = Gamma.",
        "nq3": "koopmans runs ph.x only at q = Gamma.",
        "qplot": "koopmans runs ph.x only at q = Gamma.",
        "epsil": "`task: dft_eps` is the dielectric response; it is what asks ph.x for one.",
        "trans": "`task: dft_eps` computes a dielectric response, never phonons.",
    },
    "pw2wannier90.INPUTPP": {
        "prefix": _AIIDA,
        "outdir": _AIIDA,
        "seedname": _AIIDA,
        "spin_component": f"{_SPIN} koopmans runs one pw2wannier90.x per spin channel.",
    },
    "wannier90": {
        "num_wann": "The band counts follow from `calculator_parameters.wannier90.projections`.",
        "num_bands": "The band counts follow from `calculator_parameters.wannier90.projections`.",
        "exclude_bands": (
            "Which bands each block spans follows from "
            "`calculator_parameters.wannier90.projections`."
        ),
        "unit_cell_cart": "The cell comes from the `cell_parameters` block.",
        "atoms_cart": "The atoms come from the `atomic_positions` block.",
        "atoms_frac": "The atoms come from the `atomic_positions` block.",
        "mp_grid": "The k-point mesh comes from the `kpoints` block.",
        "kpoints": "The k-point mesh comes from the `kpoints` block.",
        "auto_projections": "Set `workflow.auto_projections`.",
        "write_hr": (
            "koopmans always asks wannier90 for the gauge products; the screening and the "
            "supercell fold read them."
        ),
        "write_u_matrices": (
            "koopmans always asks wannier90 for the gauge products; the screening and the "
            "supercell fold read them."
        ),
        "write_xyz": (
            "koopmans always asks wannier90 for the gauge products; the screening and the "
            "supercell fold read them."
        ),
        "spinors": _SPIN,
        "spin": _SPIN,
    },
}


def _class_node(module: ast.Module, name: str) -> ast.ClassDef:
    """Return the class definition named ``name``.

    Raises:
        ValueError: If ``module`` declares no such class.
    """
    for node in module.body:
        if isinstance(node, ast.ClassDef) and node.name == name:
            return node
    raise ValueError(f"no class {name} in the parsed module")


def _validated_fields(node: ast.FunctionDef) -> set[str]:
    """Return the field names a ``field_validator``-decorated method covers."""
    names: set[str] = set()
    for decorator in node.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        target = decorator.func
        if isinstance(target, ast.Name) and target.id == "field_validator":
            names |= {
                argument.value
                for argument in decorator.args
                if isinstance(argument, ast.Constant) and isinstance(argument.value, str)
            }
    return names


def _kept_statements(body: list[ast.stmt], owned: frozenset[str], name: str) -> list[ast.stmt]:
    """Return the class-body statements that survive dropping ``owned``.

    Raises:
        ValueError: If an owned keyword is not a field of the class, or if a
            validator covers both a dropped and a kept field.
    """
    declared = {
        statement.target.id
        for statement in body
        if isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name)
    }
    missing = sorted(owned - declared)
    if missing:
        raise ValueError(f"{name} declares no {', '.join(missing)}; the ownership data is stale")

    kept: list[ast.stmt] = []
    for statement in body:
        if isinstance(statement, ast.Expr) and isinstance(statement.value, ast.Constant):
            continue  # the generic model's docstring; the emitted class has its own
        if isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name):
            if statement.target.id not in owned:
                kept.append(statement)
            continue
        if isinstance(statement, ast.FunctionDef):
            covered = _validated_fields(statement)
            if covered and covered <= owned:
                continue  # validates only keywords that no longer exist
            if covered & owned:
                raise ValueError(
                    f"{name}.{statement.name} validates both dropped and kept keywords "
                    f"({', '.join(sorted(covered))}); split it upstream before generating"
                )
        kept.append(statement)
    return kept


def _used_names(statements: list[ast.stmt]) -> set[str]:
    """Return every bare name the statements refer to."""
    used: set[str] = set()
    for statement in statements:
        for node in ast.walk(statement):
            if isinstance(node, ast.Name):
                used.add(node.id)
            elif isinstance(node, ast.Attribute):
                continue
    return used


def _imports(module: ast.Module, used: set[str]) -> tuple[dict[str, set[str]], set[str]]:
    """Return the ``from`` imports and plain imports covering ``used``.

    Raises:
        ValueError: If the source module uses an import alias, which the
            emitted module would have to reproduce by name.
    """
    from_imports: dict[str, set[str]] = defaultdict(set)
    plain: set[str] = set()
    for node in module.body:
        if isinstance(node, ast.ImportFrom):
            if any(alias.asname for alias in node.names):
                raise ValueError(f"aliased import from {node.module}")
            wanted = {alias.name for alias in node.names} & used
            if wanted and node.module:
                from_imports[node.module] |= wanted
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.asname:
                    raise ValueError(f"aliased import of {alias.name}")
                if alias.name.split(".")[0] in used:
                    plain.add(alias.name)
    return from_imports, plain


def _reason_map(block: str) -> dict[str, str]:
    """Return the owned keywords of ``block`` with their explanations.

    Raises:
        ValueError: If an owned keyword has no explanation, or an
            explanation names a keyword that is not owned.
    """
    owned = OWNED.get(block, frozenset())
    reasons = REASONS.get(block, {})
    unexplained = sorted(owned - reasons.keys())
    if unexplained:
        raise ValueError(
            f"{block}: {', '.join(unexplained)} would vanish from the input file with "
            f"nothing to tell whoever wrote it what to set instead. Add an entry to "
            f"koopmans.input_file._codegen.REASONS."
        )
    stale = sorted(reasons.keys() - owned)
    if stale:
        raise ValueError(
            f"{block}: {', '.join(stale)} is explained in REASONS but not owned in "
            f"aiida_koopmans.owned_keywords.OWNED."
        )
    return {keyword: reasons[keyword] for keyword in sorted(owned)}


def render(module: GeneratedModule) -> str:
    """Return the source of one generated module.

    Raises:
        ValueError: If the ownership data or the reason map is stale, or if
            a generic model's source cannot be copied faithfully.
    """
    from_imports: dict[str, set[str]] = defaultdict(set)
    plain_imports: set[str] = set()
    bodies: list[str] = []

    for model in module.models:
        source = import_module(model.source)
        tree = ast.parse(inspect.getsource(source))
        text = inspect.getsource(source)
        node = _class_node(tree, model.name)
        owned = OWNED.get(model.block, frozenset())
        reasons = _reason_map(model.block)
        kept = _kept_statements(node.body, owned, model.name)

        used = _used_names(kept) | {base.id for base in node.bases if isinstance(base, ast.Name)}
        model_from, model_plain = _imports(tree, used)
        for where, names in model_from.items():
            from_imports[where] |= names
        plain_imports |= model_plain

        lines = text.splitlines()
        segments = [_segment(lines, statement, model.name) for statement in kept]
        bases = ", ".join(ast.unparse(base) for base in node.bases)
        bodies.append(_render_class(model, bases, reasons, segments))

    from_imports["pydantic"].add("model_validator")
    from_imports["typing"].add("Any")
    from_imports["koopmans.input_file._utils"].add("raise_for_owned_keywords")

    sources = dict.fromkeys(model.source for model in module.models)
    lines = [
        _HEADER.format(
            summary=module.summary,
            sources=", ".join(f"``{source}``" for source in sources),
        )
    ]
    lines += [f"import {name}" for name in sorted(plain_imports)]
    lines += [
        f"from {where} import {', '.join(sorted(names))}"
        for where, names in sorted(from_imports.items())
    ]
    return "\n".join(lines) + "\n\n" + "\n\n".join(bodies)


def _render_class(
    model: GeneratedModel, bases: str, reasons: dict[str, str], segments: list[str]
) -> str:
    """Return the source of one generated class."""
    constant = "_" + model.block.replace(".", "_").upper() + "_OWNED"
    entries = "\n".join(f"    {keyword!r}: {reason!r}," for keyword, reason in reasons.items())
    owned_map = (
        f"#: The keywords koopmans determines, and what to set instead.\n"
        f"{constant}: dict[str, str] = {{\n{entries}\n}}\n\n\n"
        if reasons
        else ""
    )
    validator = (
        f'    @model_validator(mode="before")\n'
        f"    @classmethod\n"
        f"    def reject_owned_keywords(cls, data: Any) -> Any:\n"
        f'        """Refuse a keyword koopmans determines, naming what to set instead."""\n'
        f"        return raise_for_owned_keywords(data, {model.path!r}, {constant})\n\n"
        if reasons
        else ""
    )
    body = "\n\n".join(segments)
    declaration = f'class {model.emitted}({bases}):\n    """{model.summary}"""\n\n'
    return f"{owned_map}{declaration}{validator}{body}\n"


def _segment(lines: list[str], node: ast.stmt, name: str) -> str:
    """Return the whole source lines of one class-body statement.

    Copied by line rather than by node so a field's decorators, comments and
    line breaks come with it, and its indentation is the four spaces the
    emitted class body wants anyway.

    Raises:
        ValueError: If the statement is not indented one body deep.
    """
    if node.col_offset != 4:
        raise ValueError(f"{name} is indented {node.col_offset} spaces, not 4")
    first = node.lineno
    if isinstance(node, ast.FunctionDef) and node.decorator_list:
        first = min(decorator.lineno for decorator in node.decorator_list)
    return "\n".join(lines[first - 1 : node.end_lineno])


def generate(directory: Path | None = None) -> list[Path]:
    """Write every generated module, returning the paths written.

    Args:
        directory: Where to write. Defaults to the package's own
            ``_generated`` directory.

    Returns:
        The paths written, in :data:`MODULES` order.
    """
    ungenerated = sorted(
        OWNED.keys() - {model.block for module in MODULES for model in module.models}
    )
    if ungenerated:
        raise ValueError(
            f"aiida_koopmans.owned_keywords.OWNED claims {', '.join(ungenerated)}, which no "
            f"generated model covers, so those keywords would stay in the input file. Add "
            f"the block to koopmans.input_file._codegen.MODULES."
        )
    directory = directory or Path(__file__).parent / "_generated"
    directory.mkdir(exist_ok=True)
    (directory / "__init__.py").write_text(
        '"""Input-file models generated by ``koopmans.input_file._codegen``."""\n'
    )
    written = []
    for module in MODULES:
        path = directory / module.filename
        path.write_text(render(module))
        written.append(path)
    return written


if __name__ == "__main__":  # pragma: no cover
    import sys

    for written in generate():
        sys.stdout.write(f"{written}\n")
