"""``calculator_parameters.yambo``: the yambo BSE runcard parameters a ``bse`` task needs.

Hand-written, unlike its ``pw``/``kcw``/``wannier90`` siblings under
``calculator_parameters``: those are generated by ``koopmans.input_file._codegen``
from a package that enumerates the full upstream keyword set (``pydantic-espresso``,
``wannier90_input``); no such package exists for yambo, so there is nothing to
restrict a generic model from. Every field here is a yambo runcard variable under
its own name, read by the ``bse`` task alone (see
``aiida_koopmans.workgraphs.bethe_salpeter``, which composes a DFPT singlepoint
with a yambo BSE run seeded by its kcw.x eigenvalues in place of a GW quasiparticle
correction). Keywords the route computes or fixes for itself (``KfnQPdb``, the
BSE momentum-transfer range, the MPI role split, the arguments it always turns on)
have no field here and cannot be set; :data:`_YAMBO_REASONS` names each one and
must agree with ``aiida_koopmans.owned_keywords.OWNED["yambo"]`` (see
``tests/test_input_model_codegen.py``).
"""

from typing import Any, Self

from pydantic import Field, model_validator

from koopmans.base import BaseModel
from koopmans.input_file._utils import raise_for_owned_keywords

__all__ = ["YamboBseParameters"]

#: Yambo runcard keywords this route determines for itself, and what to read
#: instead. Kept in step with ``aiida_koopmans.owned_keywords.OWNED["yambo"]``
#: by ``tests/test_input_model_codegen.py``, the same way the generated
#: ``calculator_parameters`` blocks are kept in step with their own REASONS.
_YAMBO_REASONS: dict[str, str] = {
    "KfnQPdb": (
        "the `bse` task's own quasiparticle database: it always seeds it with the "
        "composed DFPT chain's kcw.x `ham` eigenvalues."
    ),
    "BSEQptR": (
        "koopmans always computes an optical (momentum-transfer q = 0) spectrum; the "
        "BSE momentum range follows from that."
    ),
    "BS_CPU": "Set `parallelization.yambo`; the BSE step's own MPI role split follows from its rank count.",
    "BS_ROLEs": "Set `parallelization.yambo`; the BSE step's own MPI role split follows from its rank count.",
    "rim_cut": "koopmans always turns on yambo's random-integration-method Coulomb-divergence treatment.",
    "WRbsWF": "koopmans always asks yambo to write the excitonic wavefunctions the exciton-brightness output reads.",
    "NLCC": "koopmans always turns on yambo's non-linear core correction support.",
}


class YamboBseParameters(BaseModel):
    """The yambo BSE runcard parameters a ``bse`` task needs."""

    @model_validator(mode="before")
    @classmethod
    def reject_owned_keywords(cls, data: Any) -> Any:
        """Refuse a keyword the `bse` route determines, naming what to set instead."""
        return raise_for_owned_keywords(data, "calculator_parameters.yambo", _YAMBO_REASONS)

    BndsRnXs: tuple[int, int] = Field(
        description="[first, last] band range (1-indexed, inclusive) included in the "
        "screening function W. A convergence parameter: tune it against the BSE "
        "spectrum, the way you would converge a plane-wave cutoff."
    )
    NGsBlkXs: float = Field(
        gt=0.0,
        description="G-vector cutoff, in Ry, for the screening function W. A convergence parameter.",
    )
    BSENGBlk: float | None = Field(
        default=None,
        gt=0.0,
        description="G-vector cutoff, in Ry, for the BSE kernel. Defaults to `NGsBlkXs`.",
    )
    BSEBands: tuple[int, int] = Field(
        description="[first, last] band range (1-indexed, inclusive) the BSE kernel is "
        "built over. Koopmans quasiparticle corrections exist only for the bands the "
        "DFPT chain Wannierizes, so this range must lie inside it."
    )
    BEnRange: tuple[float, float] = Field(
        description="[min, max] absorption energy window, in eV, the spectrum is computed over."
    )
    BEnSteps: int = Field(
        default=1000,
        gt=0,
        description="number of energy points sampling `BEnRange`. A numerical resolution, "
        "not a physical property of the system.",
    )
    BDmRange: tuple[float, float] = Field(
        default=(0.1, 0.1),
        description="artificial linewidth, in eV, applied to each exciton peak: "
        "[value at `BEnRange[0]`, value at `BEnRange[1]`], varied linearly across the "
        "window (equal values broaden uniformly). A numerical smoothing parameter, not "
        "a physical property of the system.",
    )

    @model_validator(mode="after")
    def default_bsengblk_to_ngsblkxs(self) -> Self:
        """Default ``BSENGBlk`` to ``NGsBlkXs`` when the caller leaves it unset."""
        if self.BSENGBlk is None:
            self.BSENGBlk = self.NGsBlkXs
        return self

    @model_validator(mode="after")
    def check_bands_ordered(self) -> Self:
        """Require ``BSEBands`` to name an ascending, positive range."""
        first, last = self.BSEBands
        if first < 1 or last < first:
            raise ValueError(
                f"`calculator_parameters.yambo.BSEBands` = [{first}, {last}] must be a "
                "positive, ascending [first, last] band range."
            )
        return self

    @model_validator(mode="after")
    def check_energy_range_ordered(self) -> Self:
        """Require ``BEnRange`` to name an ascending window."""
        low, high = self.BEnRange
        if not low < high:
            raise ValueError(
                f"`calculator_parameters.yambo.BEnRange` = [{low}, {high}] must be "
                "ascending: the minimum energy must be strictly less than the maximum."
            )
        return self

    @model_validator(mode="after")
    def check_broadening_positive(self) -> Self:
        """Require both ``BDmRange`` values to be positive."""
        if any(value <= 0 for value in self.BDmRange):
            raise ValueError(
                f"`calculator_parameters.yambo.BDmRange` = {list(self.BDmRange)} must be positive."
            )
        return self
