"""Restricted ``kcw.x`` namelists.

Generated by ``koopmans.input_file._codegen`` from
``pydantic_espresso.models.kcw.develop``.
Do not edit: run ``just generate-input-models`` instead.
"""

# ruff: noqa

from koopmans.input_file._utils import raise_for_owned_keywords, raise_for_unreachable_keywords
from pydantic import Field, field_validator, model_validator
from pydantic_espresso.namelist import Namelist
from pydantic_espresso.quantity import Quantity
from textwrap import dedent
from typing import Annotated, Any, Literal

#: The keywords koopmans determines, and what to set instead.
_KCW_CONTROL_OWNED: dict[str, str] = {
    'calculation': 'koopmans runs the kcw.x chain itself: the Wannier gauge, the screening and the Hamiltonian in turn.',
    'kcw_at_ks': 'koopmans screens Wannier functions, and always feeds kcw.x the matrices that define them.',
    'l_vcut': 'Set `workflow.gb_correction`.',
    'mp1': 'The k-point mesh comes from the `kpoints` block.',
    'mp2': 'The k-point mesh comes from the `kpoints` block.',
    'mp3': 'The k-point mesh comes from the `kpoints` block.',
    'outdir': 'AiiDA writes it for every calculation it runs.',
    'prefix': 'AiiDA writes it for every calculation it runs.',
    'read_unitary_matrix': 'koopmans screens Wannier functions, and always feeds kcw.x the matrices that define them.',
    'spin_component': 'Set `workflow.spin`. koopmans runs one kcw.x chain per spin channel.',
}


class ControlNamelist(Namelist):
    """``CONTROL`` namelist for ``kcw.x`` calculations."""

    @model_validator(mode="before")
    @classmethod
    def reject_owned_keywords(cls, data: Any) -> Any:
        """Refuse a keyword koopmans determines, naming what to set instead."""
        return raise_for_owned_keywords(data, 'calculator_parameters.kcw.control', _KCW_CONTROL_OWNED)

    @field_validator("assume_isolated", mode="before")
    @classmethod
    def map_assume_isolated(cls, v: str) -> str:
        """Map equivalent values for `assume_isolated` onto a canonical value."""
        mapping = {"m-t": "martyna-tuckerman", "mt": "martyna-tuckerman"}
        return mapping.get(v, v)

    kcw_iverbosity: Literal[0, 1, 2] = Field(
        1,
        description="Verbosity level of the KCW output.\n- '0': Minimal output.\n- '1': As above + performs additional checks.\n- '2': As above + additional infos on all the steps (any value > 1 selects this\n  verbosity tier).",
    )

    spread_thr: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.001,
        description=dedent(
            """\
            HARD-CODED FOR NOW. Two or more Wannier functions are considered identical if their
            spread (self-hartree) differ by less than spread_thr. Requires check_spread = .true."""
        ),
    )

    homo_only: bool = Field(
        False,
        description=dedent(
            """\
            If kcw_at_ks = .TRUE. only the screening paramenter for the HOMO is calculated. Mainly
            for a perturbative calculation of the first Ionization Potential in isolated systems."""
        ),
    )

    assume_isolated: Literal["none", "martyna-tuckerman"] = Field(
        "none",
        description=dedent(
            """\
            Used to perform calculation assuming the system to be isolated (a molecule or a cluster
            in a 3D supercell).  Currently available choices:
            - 'none': regular periodic calculation w/o any correction.
            - 'martyna-tuckerman': Martyna-Tuckerman correction to both total energy and scf
              potential. Adapted from: G.J. Martyna, and M.E. Tuckerman, 'A reciprocal space based
              method for treating long range interactions in ab-initio and force-field-based
              calculation in clusters', J. Chem. Phys. 110, 2810 (1999), doi:10.1063/1.477923
              (https://doi.org/10.1063/1.477923)."""
        ),
    )

    lrpa: bool = Field(
        False,
        description='If .true. the response function is computed neglecting xc effects both in the kernel\nand in the response function (RPA).',
    )

    io_sp: bool = Field(
        False, description="If .true. write wannier orbital densities in single-precision."
    )

    io_real_space: bool = Field(
        False,
        description=dedent(
            """\
            If .true. write Wannier orbital densities and Wannier functions in real space."""
        ),
    )

    irr_bz: bool = Field(
        False,
        description=dedent(
            """\
            If .true. compute and use the symmetries of the Wannier orbital densities to reduce the
            number of k and q points for the BZ sampling."""
        ),
    )

    use_wct: bool = Field(
        False,
        description=dedent(
            """\
            If .true. allow to use symmetries that send the Wannier orbital density into the
            Wannier translated by a lattice vector (wcf= wannier center translation) to further
            reduce the number of q points"""
        ),
    )


#: The keywords koopmans determines, and what to set instead.
_KCW_WANNIER_OWNED: dict[str, str] = {
    'has_disentangle': 'Whether the empty manifold is disentangled follows from `calculator_parameters.wannier90.projections` and the band count.',
    'have_empty': 'Whether there is an empty manifold follows from `calculator_parameters.wannier90.projections`.',
    'num_wann_emp': 'The manifold sizes follow from `calculator_parameters.wannier90.projections`.',
    'num_wann_occ': 'The manifold sizes follow from `calculator_parameters.wannier90.projections`.',
    'seedname': 'koopmans writes the wannier90 products under one seedname and points kcw.x at them.',
}


#: The keywords koopmans cannot pass through, and why.
_KCW_WANNIER_UNREACHABLE: dict[str, str] = {
    'alpha_mix': 'kcw.x reads `alpha_mix` from its `SCREEN` namelist, and the model this block is generated from declares it under `WANNIER`, where kcw.x aborts reading the namelist. koopmans cannot pass it through until that is fixed upstream; the screening runs at the kcw.x default.',
}


class WannierNamelist(Namelist):
    """``WANNIER`` namelist for ``kcw.x`` calculations."""

    @model_validator(mode="before")
    @classmethod
    def reject_owned_keywords(cls, data: Any) -> Any:
        """Refuse a keyword koopmans determines, naming what to set instead."""
        return raise_for_owned_keywords(data, 'calculator_parameters.kcw.wannier', _KCW_WANNIER_OWNED)

    @model_validator(mode="before")
    @classmethod
    def reject_unreachable_keywords(cls, data: Any) -> Any:
        """Refuse a keyword koopmans cannot pass through, saying why."""
        return raise_for_unreachable_keywords(data, 'calculator_parameters.kcw.wannier', _KCW_WANNIER_UNREACHABLE)

    check_ks: bool = Field(
        True,
        description="Specify if a diagonalization of the KS matrix build using the wannier function in input\nhas to be performed. This is mainly for debugging purpose.\n\nkoopmans seeds True; kcw.x's own default is False.",
    )


#: The keywords koopmans determines, and what to set instead.
_KCW_SCREEN_OWNED: dict[str, str] = {
    'check_spread': 'koopmans matches the kcw.x spread shortcut to how it screens; set `workflow.group_orbitals_by` to group orbitals.',
    'eps_inf': 'Set `workflow.eps_inf`.',
    'i_orb': 'koopmans screens every orbital at once, or one representative per group; `workflow.group_orbitals_by` chooses which.',
}


class ScreenNamelist(Namelist):
    """``SCREEN`` namelist for ``kcw.x`` calculations."""

    @model_validator(mode="before")
    @classmethod
    def reject_owned_keywords(cls, data: Any) -> Any:
        """Refuse a keyword koopmans determines, naming what to set instead."""
        return raise_for_owned_keywords(data, 'calculator_parameters.kcw.screen', _KCW_SCREEN_OWNED)

    niter: int | None = Field(
        33,
        description="Maximum number of iterations in a scf step. If you want more than 100, edit variable\n'maxter' in PH/phcom.f90\n\nkoopmans seeds 33; kcw.x derives its own default.",
        json_schema_extra={'default_ref': ''},
    )

    nmix: int = Field(
        4,
        description='Number of iterations used in potential mixing.',
    )

    tr2: float = Field(
        1e-18,
        description="Threshold for self-consistency.\n\nkoopmans seeds 1e-18; kcw.x's own default is 1e-14.",
    )


#: The keywords koopmans determines, and what to set instead.
_KCW_HAM_OWNED: dict[str, str] = {
    'do_bands': 'An interpolated band structure runs whenever `kpoints.path` gives a path.',
}


class HamNamelist(Namelist):
    """``HAM`` namelist for ``kcw.x`` calculations."""

    @model_validator(mode="before")
    @classmethod
    def reject_owned_keywords(cls, data: Any) -> Any:
        """Refuse a keyword koopmans determines, naming what to set instead."""
        return raise_for_owned_keywords(data, 'calculator_parameters.kcw.ham', _KCW_HAM_OWNED)

    use_ws_distance: bool = Field(
        True,
        description='If .true. the position of the Wannier function inside the cell is used to set the\nproper distance and to have a smoother interpolation. Requires seedname_centres.xyz to\nbe printed by the previous Wannier90 run. If the file is not found it is automatically\nswitched to .FALSE. and only the distance between the cells is used (see also Wannier90\ndocumentation)',
    )

    write_hr: bool = Field(
        True,
        description='If .true. the KCW hamiltonain in the Wannier basis and in real spase H(R)_m_n is\nprinted to file. Usefull for furhter post-processing.',
    )

    on_site_only: bool = Field(
        False,
        description='If .true. only the on-site and diagonal elements of the KCW hamiltonain are computed\n(R=0 and n=m).',
    )
