"""Restricted ``pw.x`` namelists.

Generated by ``koopmans.input_file._codegen`` from
``pydantic_espresso.models.pw.develop``.
Do not edit: run ``just generate-input-models`` instead.
"""

# ruff: noqa

from koopmans.input_file._utils import raise_for_owned_keywords
from pathlib import Path
from pydantic import Field, field_validator, model_validator
from pydantic_espresso.namelist import Namelist
from pydantic_espresso.quantity import Quantity
from textwrap import dedent
from typing import Annotated, Any, Literal

#: The keywords koopmans determines, and what to set instead.
_CONTROL_NAMELIST_OWNED: dict[str, str] = {
    'outdir': 'AiiDA writes it for every calculation it runs.',
    'prefix': 'AiiDA writes it for every calculation it runs.',
    'pseudo_dir': 'Pseudopotentials come from `workflow.pseudo_library`.',
    'verbosity': 'koopmans needs every eigenvalue pw.x can print, so it always runs at high verbosity.',
}


class _ControlNamelist(Namelist):
    """``CONTROL`` namelist for ``pw.x``, less the keywords koopmans determines."""

    @model_validator(mode="before")
    @classmethod
    def reject_owned_keywords(cls, data: Any) -> Any:
        """Refuse a keyword koopmans determines, naming what to set instead."""
        return raise_for_owned_keywords(data, 'calculator_parameters.pw.control', _CONTROL_NAMELIST_OWNED)

    calculation: Literal["scf", "nscf", "bands", "relax", "md", "vc-relax", "vc-md"] = Field(
        "scf",
        description=dedent(
            """\
            A string describing the task to be performed. Options are:  (vc = variable-cell)."""
        ),
    )

    title: str | None = Field(None, description="reprinted on output.")

    restart_mode: Literal["from_scratch", "restart"] = Field(
        "from_scratch",
        description=dedent(
            """\
            Available options are:
            - 'from_scratch': From scratch. This is the normal way to perform a PWscf calculation.
            - 'restart': From previous interrupted run. Use this switch only if you want to
              continue, using the same number of processors and parallelization, an interrupted
              calculation. Do not use to start a new one, or to perform a non-scf calculations.
              Works only if the calculation was cleanly stopped using variable max_seconds, or by
              user request with an 'exit file' (i.e.: create a file 'prefix'.EXIT, in directory
              'outdir'; see variables prefix, outdir). The default for startingwfc and startingpot
              is set to 'file'."""
        ),
    )

    nstep: int | None = Field(
        None,
        json_schema_extra={
            "conditional_default": [
                {
                    "when": "calculation=='scf' || calculation=='nscf' || calculation=='bands'",
                    "value": "1",
                },
                {"when": None, "value": "50"},
            ],
        },
        description=dedent(
            """\
            number of molecular-dynamics or structural optimization steps performed in this run. If
            set to 0, the code performs a quick 'dry run', stopping just after initialization. This
            is useful to check for input correctness and to have the summary printed. NOTE: in MD
            calculations, the code will perform 'nstep' steps even if restarting from a previously
            interrupted calculation."""
        ),
    )

    iprint: int = Field(
        100000,
        description=dedent(
            """\
            When calculation == 'md' (molecular dynamics) trajectory is written every iprint md
            steps. With the default value, output is written only at convergence."""
        ),
    )

    tstress: bool = Field(
        False,
        description=dedent(
            """\
            calculate stress. It is set to .TRUE. automatically if calculation == 'vc-md' or
            'vc-relax"""
        ),
    )

    tprnfor: bool = Field(
        False,
        description=dedent(
            """\
            calculate forces. It is set to .TRUE. automatically if calculation ==
            'relax','md','vc-md"""
        ),
    )

    dt: Annotated[
        float, Quantity(units="bohr electron_mass^1/2 Ry^-1/2", dimensionality="time")
    ] = Field(
        20.0,
        description=dedent(
            """\
            time step for molecular dynamics, in Rydberg atomic units (1 a.u.=4.8378 * 10^-17 s :
            beware, the CP code uses Hartree atomic units, half that much!!!)"""
        ),
    )

    wfcdir: Path | None = Field(
        None,
        json_schema_extra={"default_ref": "outdir"},
        description=dedent(
            """\
            This directory specifies where to store files generated by each processor (*.wfc{N},
            *.igk{N}, etc.). Useful for machines without a parallel file system: set wfcdir to a
            local file system, while outdir should be a parallel or network file system, visible to
            all processors. Beware: in order to restart from interrupted runs, or to perform
            further calculations using the produced data files, you may need to copy files to
            outdir. Works only for pw.x."""
        ),
    )

    max_seconds: Annotated[float, Quantity(units="s", dimensionality="time")] = Field(
        10000000.0,
        description=dedent(
            """\
            Jobs stops after max_seconds CPU time. Use this option in conjunction with option
            restart_mode if you need to split a job too long to complete into shorter jobs that fit
            into your batch queues. The default value (10000000 s, about 150 days) effectively
            means that no time limit is imposed."""
        ),
    )

    etot_conv_thr: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.0001,
        description=dedent(
            """\
            Convergence threshold on total energy (a.u) for ionic minimization: the convergence
            criterion is satisfied when the total energy changes less than etot_conv_thr between
            two consecutive scf steps. Note that etot_conv_thr is extensive, like the total energy.
            See also forc_conv_thr - both criteria must be satisfied"""
        ),
    )

    forc_conv_thr: Annotated[
        float, Quantity(units="Ry bohr^-1", dimensionality="energy length^-1")
    ] = Field(
        0.001,
        description=dedent(
            """\
            Convergence threshold on forces for ionic minimization: the convergence criterion is
            satisfied when all components of all forces are smaller than forc_conv_thr. See also
            etot_conv_thr - both criteria must be satisfied"""
        ),
    )

    disk_io: Literal["default", "high", "medium", "low", "nowf", "minimal", "none"] = Field(
        "default",
        description=dedent(
            """\
            Specifies the amount of disk I/O activity: (only for binary files and xml data file in
            data directory; other files printed at each molecular dynamics / structural
            optimization step are not controlled by this option )  Default is 'low' for the scf
            case, 'medium' otherwise. Note that the needed RAM increases as disk I/O decreases
            - 'default': the amount of disk I/O is chosen automatically depending on the kind of
              calculation.
            - 'high': save charge to disk at each SCF step, keep wavefunctions on disk (in
              'distributed' format), save mixing data as well. Do not use this option unless you
              have a good reason! It is no longer needed to specify 'high' in order to be able to
              restart from an interrupted calculation (see restart_mode).
            - 'medium': save charge to disk at each SCF step, keep wavefunctions on disk only if
              more than one k-point, per process is present, otherwise keep them in memory; save
              them to disk only at the end (in 'portable' format).
            - 'low': save charge to disk at each SCF step, keep wavefunctions in memory (for all
              k-points), save them to disk only at the end (in 'portable' format). Reduces I/O but
              increases memory wrt the previous cases.
            - 'nowf': save to disk only the xml data file and the charge density at convergence,
              never save wavefunctions. Restarting from an interrupted calculation is not possible
              with this option.
            - 'minimal': save to disk only the xml data file at convergence.
            - 'none': do not save anything to disk."""
        ),
    )

    tefield: bool = Field(
        False,
        description=dedent(
            """\
            If .TRUE. a saw-like potential simulating an electric field is added to the bare ionic
            potential. See variables edir, eamp, emaxpos, eopreg for the form and size of the added
            potential."""
        ),
    )

    dipfield: bool = Field(
        False,
        description=dedent(
            """\
            If .TRUE. and tefield==.TRUE. a dipole correction is also added to the bare ionic
            potential - implements the recipe of L. Bengtsson, PRB 59, 12301 (1999)
            (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.59.12301). See variables edir,
            emaxpos, eopreg for the form of the correction. Must be used ONLY in a slab geometry,
            for surface calculations, with the discontinuity FALLING IN THE EMPTY SPACE."""
        ),
    )

    lelfield: bool = Field(
        False,
        description=dedent(
            """\
            If .TRUE. a homogeneous finite electric field described through the modern theory of
            the polarization is applied. This is different from tefield == .true. !"""
        ),
    )

    nberrycyc: int = Field(
        1,
        description=dedent(
            """\
            In the case of a finite electric field  ( lelfield == .TRUE. ) it defines the number of
            iterations for converging the wavefunctions in the electric field Hamiltonian, for each
            external iteration on the charge density"""
        ),
    )

    lorbm: bool = Field(
        False,
        description=dedent(
            """\
            If .TRUE. perform orbital magnetization calculation. If finite electric field is
            applied (lelfield==.true.) only Kubo terms are computed [for details see New J. Phys.
            12, 053032 (2010), doi:10.1088/1367-2630/12/5/053032
            (https://doi.org/10.1088/1367-2630/12/5/053032)].  The type of calculation is 'nscf'
            and should be performed on an automatically generated uniform grid of k points.  Works
            ONLY with norm-conserving pseudopotentials."""
        ),
    )

    lberry: bool = Field(
        False,
        description=dedent(
            """\
            If .TRUE. perform a Berry phase calculation. See the header of PW/src/bp_c_phase.f90
            for documentation."""
        ),
    )

    gdir: Literal[0, 1, 2, 3] = Field(
        0,
        description=dedent(
            """\
            For Berry phase calculation: direction of the k-point strings in reciprocal space. For
            calculations with finite electric fields (lelfield == .true.) this is the direction of
            the field. A value of 1, 2 or 3 is required when lberry == .true. or lelfield ==
            .true.; PW/src/setup.f90 raises an error otherwise.
            - '0': No Berry-phase or finite-field calculation requested (the value is unused).
            - '1': first reciprocal lattice vector.
            - '2': second reciprocal lattice vector.
            - '3': third reciprocal lattice vector."""
        ),
    )

    nppstr: int = Field(
        0,
        description=dedent(
            """\
            For Berry phase calculation: number of k-points to be calculated along each
            symmetry-reduced string. The same for calculation with finite electric fields
            (lelfield==.true.)."""
        ),
    )

    gate: bool = Field(
        False,
        description=dedent(
            """\
            In the case of charged cells (tot_charge .ne. 0) setting gate = .TRUE. represents the
            counter charge (i.e. -tot_charge) not by a homogeneous background charge but with a
            charged plate, which is placed at zgate (see below). Details of the gate potential can
            be found in T. Brumme, M. Calandra, F. Mauri; PRB 89, 245406 (2014)
            (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.89.245406). Note, that in
            systems which are not symmetric with respect to the plate, one needs to enable the
            dipole correction! (dipfield=.true.). Currently, symmetry can be used with gate=.true.
            but carefully check that no symmetry is included which maps z to -z even if in
            principle one could still use them for symmetric systems (i.e. no dipole correction).
            For nosym=.false. verbosity is set to 'high'. Note: this option was called 'monopole'
            in v6.0 and 6.1 of pw.x"""
        ),
    )

    twochem: bool = Field(
        False,
        description=dedent(
            """\
            IF .TRUE. , a two chemical potential calculation for the simulation of photoexcited
            systems is performed, constraining a fraction of the electrons in the conduction
            manifold. See G. Marini, M. Calandra; PRB 104, 144103 (2021)
            (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.104.144103). Note: requires
            occupations to be set to 'smearing'."""
        ),
    )

    lfcp: bool = Field(
        False,
        description=dedent(
            """\
            If .TRUE. perform a constant bias potential (constant-mu) calculation for a system with
            ESM method. See the header of PW/src/fcp_module.f90 for documentation. To perform the
            calculation, you must set a namelist FCP.  NB: - The total energy displayed in output
            includes the potentiostat contribution (-mu*N). - calculation must be 'relax' or 'md'.
            - assume_isolated = 'esm' and esm_bc = 'bc2' or 'bc3' must be set in SYSTEM namelist. -
            ESM-RISM is also supported (assume_isolated = 'esm' and esm_bc = 'bc1' and trism =
            .TRUE.). - ignore_wolfe is always .TRUE., for BFGS."""
        ),
    )

    trism: bool = Field(
        False,
        description=dedent(
            """\
            If .TRUE. perform a 3D-RISM-SCF calculation [for details see H.Sato et al., JCP 112,
            9463 (2000), doi:10.1063/1.481564 (https://doi.org/10.1063/1.481564)]. The solvent's
            distributions are calculated by 3D-RISM, though solute is treated as SCF. The charge
            density and the atomic positions are optimized, simultaneously with the solvents. To
            perform the calculation, you must set a namelist RISM and a card SOLVENTS.  If
            assume_isolated = 'esm' and esm_bc = 'bc1', Laue-RISM is calculated instead of 3D-RISM
            and coupled with ESM method (i.e. ESM-RISM). [for details see S.Nishihara and M.Otani,
            PRB 96, 115429 (2017)
            (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.96.115429)].  The default of
            mixing_beta is 0.2 for both 3D-RISM and Laue-RISM.  For structural relaxation with
            BFGS, ignore_wolfe is always .TRUE. ."""
        ),
    )


#: The keywords koopmans determines, and what to set instead.
_SYSTEM_NAMELIST_OWNED: dict[str, str] = {
    'ecutrho': 'Set `calculator_parameters.ecutwfc`: pw.x and kcp.x always share one grid, and `ecutrho` follows at four times it.',
    'ecutwfc': 'Set `calculator_parameters.ecutwfc`: pw.x and kcp.x always share one grid, and `ecutrho` follows at four times it.',
    'ibrav': 'The lattice comes from the `cell_parameters` block.',
    'lspinorb': 'Set `workflow.spin`.',
    'nat': 'The atoms come from the `atomic_positions` block.',
    'noncolin': 'Set `workflow.spin`.',
    'nspin': 'Set `workflow.spin`.',
    'ntyp': 'The species come from the `atomic_positions` block.',
}


class _SystemNamelist(Namelist):
    """``SYSTEM`` namelist for ``pw.x``, less the keywords koopmans determines."""

    @model_validator(mode="before")
    @classmethod
    def reject_owned_keywords(cls, data: Any) -> Any:
        """Refuse a keyword koopmans determines, naming what to set instead."""
        return raise_for_owned_keywords(data, 'calculator_parameters.pw.system', _SYSTEM_NAMELIST_OWNED)

    @field_validator("smearing", mode="before")
    @classmethod
    def map_smearing(cls, v: str) -> str:
        """Map equivalent values for `smearing` onto a canonical value."""
        mapping = {
            "gauss": "gaussian",
            "m-p": "methfessel-paxton",
            "mp": "methfessel-paxton",
            "cold": "marzari-vanderbilt",
            "m-v": "marzari-vanderbilt",
            "mv": "marzari-vanderbilt",
            "f-d": "fermi-dirac",
            "fd": "fermi-dirac",
        }
        return mapping.get(v, v)

    @field_validator("assume_isolated", mode="before")
    @classmethod
    def map_assume_isolated(cls, v: str) -> str:
        """Map equivalent values for `assume_isolated` onto a canonical value."""
        mapping = {
            "m-p": "makov-payne",
            "mp": "makov-payne",
            "m-t": "martyna-tuckerman",
            "mt": "martyna-tuckerman",
        }
        return mapping.get(v, v)

    @field_validator("vdw_corr", mode="before")
    @classmethod
    def map_vdw_corr(cls, v: str) -> str:
        """Map equivalent values for `vdw_corr` onto a canonical value."""
        mapping = {
            "Grimme-D2": "grimme-d2",
            "DFT-D": "grimme-d2",
            "dft-d": "grimme-d2",
            "Grimme-D3": "grimme-d3",
            "DFT-D3": "grimme-d3",
            "dft-d3": "grimme-d3",
            "TS": "tkatchenko-scheffler",
            "ts": "tkatchenko-scheffler",
            "ts-vdw": "tkatchenko-scheffler",
            "ts-vdW": "tkatchenko-scheffler",
            "MBD": "many-body-dispersion",
            "mbd": "many-body-dispersion",
            "mbd_vdw": "many-body-dispersion",
            "xdm": "XDM",
        }
        return mapping.get(v, v)

    A: Annotated[float, Quantity(units="angstrom", dimensionality="length")] = Field(
        0.0,
        description=dedent(
            """\
            Traditional crystallographic constants:  a,b,c in ANGSTROM cosAB = cosine of the angle
            between axis a and b (gamma) cosAC = cosine of the angle between axis a and c (beta)
            cosBC = cosine of the angle between axis b and c (alpha)  The axis are chosen according
            to the value of ibrav. Specify either these OR celldm but NOT both. Only needed values
            (depending on ibrav) must be specified.  The lattice parameter alat = A (in ANGSTROM ).
             If ibrav == 0, only A is used if present, and cell vectors are read from card
            CELL_PARAMETERS."""
        ),
    )

    B: Annotated[float, Quantity(units="angstrom", dimensionality="length")] = Field(
        0.0,
        description=dedent(
            """\
            Traditional crystallographic constants:  a,b,c in ANGSTROM cosAB = cosine of the angle
            between axis a and b (gamma) cosAC = cosine of the angle between axis a and c (beta)
            cosBC = cosine of the angle between axis b and c (alpha)  The axis are chosen according
            to the value of ibrav. Specify either these OR celldm but NOT both. Only needed values
            (depending on ibrav) must be specified.  The lattice parameter alat = A (in ANGSTROM ).
             If ibrav == 0, only A is used if present, and cell vectors are read from card
            CELL_PARAMETERS."""
        ),
    )

    C: Annotated[float, Quantity(units="angstrom", dimensionality="length")] = Field(
        0.0,
        description=dedent(
            """\
            Traditional crystallographic constants:  a,b,c in ANGSTROM cosAB = cosine of the angle
            between axis a and b (gamma) cosAC = cosine of the angle between axis a and c (beta)
            cosBC = cosine of the angle between axis b and c (alpha)  The axis are chosen according
            to the value of ibrav. Specify either these OR celldm but NOT both. Only needed values
            (depending on ibrav) must be specified.  The lattice parameter alat = A (in ANGSTROM ).
             If ibrav == 0, only A is used if present, and cell vectors are read from card
            CELL_PARAMETERS."""
        ),
    )

    cosAB: float = Field(  # noqa: N815
        0.0,
        description=dedent(
            """\
            Traditional crystallographic constants:  a,b,c in ANGSTROM cosAB = cosine of the angle
            between axis a and b (gamma) cosAC = cosine of the angle between axis a and c (beta)
            cosBC = cosine of the angle between axis b and c (alpha)  The axis are chosen according
            to the value of ibrav. Specify either these OR celldm but NOT both. Only needed values
            (depending on ibrav) must be specified.  The lattice parameter alat = A (in ANGSTROM ).
             If ibrav == 0, only A is used if present, and cell vectors are read from card
            CELL_PARAMETERS."""
        ),
    )

    cosAC: float = Field(  # noqa: N815
        0.0,
        description=dedent(
            """\
            Traditional crystallographic constants:  a,b,c in ANGSTROM cosAB = cosine of the angle
            between axis a and b (gamma) cosAC = cosine of the angle between axis a and c (beta)
            cosBC = cosine of the angle between axis b and c (alpha)  The axis are chosen according
            to the value of ibrav. Specify either these OR celldm but NOT both. Only needed values
            (depending on ibrav) must be specified.  The lattice parameter alat = A (in ANGSTROM ).
             If ibrav == 0, only A is used if present, and cell vectors are read from card
            CELL_PARAMETERS."""
        ),
    )

    cosBC: float = Field(  # noqa: N815
        0.0,
        description=dedent(
            """\
            Traditional crystallographic constants:  a,b,c in ANGSTROM cosAB = cosine of the angle
            between axis a and b (gamma) cosAC = cosine of the angle between axis a and c (beta)
            cosBC = cosine of the angle between axis b and c (alpha)  The axis are chosen according
            to the value of ibrav. Specify either these OR celldm but NOT both. Only needed values
            (depending on ibrav) must be specified.  The lattice parameter alat = A (in ANGSTROM ).
             If ibrav == 0, only A is used if present, and cell vectors are read from card
            CELL_PARAMETERS."""
        ),
    )

    nbnd: int | None = Field(
        None,
        json_schema_extra={"computed_default": True},
        description=dedent(
            """\
            Number of electronic states (bands) to be calculated. Note that in spin-polarized
            calculations the number of k-point, not the number of bands per k-point, is doubled  By
            default, for an insulator nbnd is set to the number of valence bands (nbnd = number of
            electrons / 2); for a metal, 20% more (with a minimum of 4 more) states are added."""
        ),
    )

    nbnd_cond: int | None = Field(
        None,
        json_schema_extra={"computed_default": True},
        description=dedent(
            """\
            Number of electronic states in the conduction manifold for a two chemical-potential
            calculation (twochem=.true.).  By default it is set to nbnd - (number of electrons / 2)
            in the collinear case, and to nbnd - (number of electrons) in the noncollinear case."""
        ),
    )

    tot_charge: Annotated[float, Quantity(units="e", dimensionality="charge")] = Field(
        0.0,
        description=dedent(
            """\
            Total charge of the system. Useful for simulations with charged cells. By default the
            unit cell is assumed to be neutral (tot_charge=0). tot_charge=+1 means one electron
            missing from the system, tot_charge=-1 means one additional electron, and so on.  In a
            periodic calculation a compensating jellium background is inserted to remove
            divergences if the cell is not neutral."""
        ),
    )

    tot_magnetization: float = Field(
        -10000,
        description=dedent(
            """\
            Total majority spin charge - minority spin charge. Used to impose a specific total
            electronic magnetization. The default value -10000 is a sentinel meaning 'unspecified':
            if left unspecified the tot_magnetization variable is ignored and the amount of
            electronic magnetization is determined during the self-consistent cycle."""
        ),
    )

    ecutfock: Annotated[float | None, Quantity(units="Ry", dimensionality="energy")] = Field(
        None,
        json_schema_extra={"default_ref": "ecutrho"},
        description=dedent(
            """\
            Kinetic energy cutoff for the exact exchange operator in EXX type calculations. By
            default this is the same as ecutrho but in some EXX calculations, a significant
            speed-up can be obtained by reducing ecutfock, at the expense of some loss in accuracy.
            Must be .gt. ecutwfc. Not implemented for stress calculation and for US-PP and PAW
            pseudopotentials. Use with care, especially in metals where it may give raise to
            instabilities."""
        ),
    )

    nr1: int = Field(
        0,
        description=dedent(
            """\
            Three-dimensional FFT mesh (hard grid) for charge density (and scf potential). If not
            specified the grid is calculated based on the cutoff for charge density (see also
            ecutrho) Note: you must specify all three dimensions for this setting to be used."""
        ),
    )

    nr2: int = Field(
        0,
        description=dedent(
            """\
            Three-dimensional FFT mesh (hard grid) for charge density (and scf potential). If not
            specified the grid is calculated based on the cutoff for charge density (see also
            ecutrho) Note: you must specify all three dimensions for this setting to be used."""
        ),
    )

    nr3: int = Field(
        0,
        description=dedent(
            """\
            Three-dimensional FFT mesh (hard grid) for charge density (and scf potential). If not
            specified the grid is calculated based on the cutoff for charge density (see also
            ecutrho) Note: you must specify all three dimensions for this setting to be used."""
        ),
    )

    nr1s: int = Field(
        0,
        description=dedent(
            """\
            Three-dimensional mesh for wavefunction FFT and for the smooth part of charge density (
            smooth grid ). Coincides with nr1, nr2, nr3 if ecutrho = 4 * ecutwfc ( default ) Note:
            you must specify all three dimensions for this setting to be used."""
        ),
    )

    nr2s: int = Field(
        0,
        description=dedent(
            """\
            Three-dimensional mesh for wavefunction FFT and for the smooth part of charge density (
            smooth grid ). Coincides with nr1, nr2, nr3 if ecutrho = 4 * ecutwfc ( default ) Note:
            you must specify all three dimensions for this setting to be used."""
        ),
    )

    nr3s: int = Field(
        0,
        description=dedent(
            """\
            Three-dimensional mesh for wavefunction FFT and for the smooth part of charge density (
            smooth grid ). Coincides with nr1, nr2, nr3 if ecutrho = 4 * ecutwfc ( default ) Note:
            you must specify all three dimensions for this setting to be used."""
        ),
    )

    nosym: bool = Field(
        False,
        description=dedent(
            """\
            if (.TRUE.) symmetry is not used. Consequences:  - if a list of k points is provided in
            input, it is used 'as is': symmetry-inequivalent k-points are not generated, and the
            charge density is not symmetrized;  - if a uniform (Monkhorst-Pack) k-point grid is
            provided in input, it is expanded to cover the entire Brillouin Zone, irrespective of
            the crystal symmetry. Time reversal symmetry is assumed so k and -k are considered as
            equivalent unless noinv=.true. is specified.  Do not use this option unless you know
            exactly what you want and what you get. May be useful in the following cases: - in
            low-symmetry large cells, if you cannot afford a k-point grid with the correct symmetry
            - in MD simulations - in calculations for isolated atoms"""
        ),
    )

    nosym_evc: bool = Field(
        False,
        description=dedent(
            """\
            if (.TRUE.) symmetry is not used, and k points are forced to have the symmetry of the
            Bravais lattice; an automatically generated Monkhorst-Pack grid will contain all points
            of the grid over the entire Brillouin Zone, plus the points rotated by the symmetries
            of the Bravais lattice which were not in the original grid. The same applies if a
            k-point list is provided in input instead of a Monkhorst-Pack grid. Time reversal
            symmetry is assumed so k and -k are equivalent unless noinv=.true. is specified. This
            option differs from nosym because it forces k-points in all cases to have the full
            symmetry of the Bravais lattice (not all uniform grids have such property!)"""
        ),
    )

    noinv: bool = Field(
        False,
        description=dedent(
            """\
            if (.TRUE.) disable the usage of k => -k symmetry (time reversal) in k-point
            generation"""
        ),
    )

    no_t_rev: bool = Field(
        False,
        description=dedent(
            """\
            if (.TRUE.) disable the usage of magnetic symmetry operations that consist in a
            rotation + time reversal."""
        ),
    )

    force_symmorphic: bool = Field(
        False,
        description=dedent(
            """\
            if (.TRUE.) force the symmetry group to be symmorphic by disabling symmetry operations
            having an associated fractionary translation"""
        ),
    )

    use_all_frac: bool = Field(
        False,
        description=dedent(
            """\
            if (.FALSE.) force real-space FFT grids to be commensurate with fractionary
            translations of non-symmorphic symmetry operations, if present (e.g.: if a fractional
            translation (0,0,c/4) exists, the FFT dimension along the c axis must be multiple of
            4). if (.TRUE.) do not impose any constraints to FFT grids, even in the presence of
            non-symmorphic symmetry operations. BEWARE: use_all_frac=.TRUE. may lead to wrong
            results for hybrid functionals and phonon calculations. Both cases use symmetrization
            in real space that works for non-symmorphic operations only if the real-space FFT grids
            are commensurate."""
        ),
    )

    occupations: Literal[
        "smearing", "tetrahedra", "tetrahedra_lin", "tetrahedra_opt", "fixed", "from_input"
    ] = Field(
        "fixed",
        description=dedent(
            """\
            Available options are:
            - 'smearing': gaussian smearing for metals; see variables smearing and degauss.
            - 'tetrahedra': Tetrahedron method, Bloechl's version: P.E. Bloechl, PRB 49, 16223
              (1994) (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.49.16223) Requires
              uniform grid of k-points, to be automatically generated (see card K_POINTS). Well
              suited for calculation of DOS, less so (because not variational) for
              force/optimization/dynamics calculations.
            - 'tetrahedra_lin': Original linear tetrahedron method. To be used only as a reference;
              the optimized tetrahedron method is more efficient.
            - 'tetrahedra_opt': Optimized tetrahedron method: see M. Kawamura, PRB 89, 094515
              (2014) (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.89.094515). Can be
              used for phonon calculations as well.
            - 'fixed': for insulators with a gap.
            - 'from_input': The occupation are read from input file, card OCCUPATIONS. Option valid
              only for a single k-point, requires nbnd to be set in input. Occupations should be
              consistent with the value of tot_charge."""
        ),
    )

    one_atom_occupations: bool = Field(
        False,
        description=dedent(
            """\
            This flag is used for isolated atoms (nat=1) together with occupations='from_input'. If
            it is .TRUE., the wavefunctions are ordered as the atomic starting wavefunctions,
            independently from their eigenvalue. The occupations indicate which atomic states are
            filled.  The order of the states is written inside the UPF pseudopotential file. In the
            scalar relativistic case: S -> l=0, m=0 P -> l=1, z, x, y D -> l=2, r^2-3z^2, xz, yz,
            xy, x^2-y^2  In the noncollinear magnetic case (with or without spin-orbit), each group
            of states is doubled. For instance: P -> l=1, z, x, y for spin up, l=1, z, x, y for
            spin down. Up and down is relative to the direction of the starting magnetization.  In
            the case with spin-orbit and time-reversal (starting_magnetization=0.0) the atomic
            wavefunctions are radial functions multiplied by spin-angle functions. For instance: P
            -> l=1, j=1/2, m_j=-1/2,1/2. l=1, j=3/2, m_j=-3/2, -1/2, 1/2, 3/2.  In the magnetic
            case with spin-orbit the atomic wavefunctions can be forced to be spin-angle functions
            by setting starting_spin_angle to .TRUE.."""
        ),
    )

    starting_spin_angle: bool = Field(
        False,
        description=dedent(
            """\
            In the spin-orbit case when domag=.TRUE., by default, the starting wavefunctions are
            initialized as in scalar relativistic noncollinear case without spin-orbit.  By setting
            starting_spin_angle=.TRUE. this behaviour can be changed and the initial wavefunctions
            are radial functions multiplied by spin-angle functions.  When domag=.FALSE. the
            initial wavefunctions are always radial functions multiplied by spin-angle functions
            independently from this flag.  When lspinorb is .FALSE. this flag is not used."""
        ),
    )

    degauss_cond: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.0,
        description=dedent(
            """\
            value of the gaussian spreading for brillouin-zone integration in the conduction
            manifold in a two-chemical potential calculation (twochem=.true.)."""
        ),
    )

    nelec_cond: float = Field(
        0.0,
        description=dedent(
            """\
            Number of electrons placed in the conduction manifold in a two-chemical potential
            calculation (twochem=.true.). Of the total # of electrons nelec, nelec-nelec_cond will
            occupy the valence manifold and nelec_cond will be constrained in the conduction
            manifold."""
        ),
    )

    degauss: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.0, description="value of the gaussian spreading for brillouin-zone integration in metals."
    )

    smearing: Literal["gaussian", "methfessel-paxton", "marzari-vanderbilt", "fermi-dirac"] = Field(
        "gaussian",
        description=dedent(
            """\
            Available options are:
            - 'gaussian': ordinary Gaussian spreading.
            - 'methfessel-paxton': Methfessel-Paxton first-order spreading (see PRB 40, 3616 (1989)
              (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.40.3616)).
            - 'marzari-vanderbilt': Marzari-Vanderbilt-DeVita-Payne cold smearing (see PRL 82, 3296
              (1999) (https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.82.3296)).
            - 'fermi-dirac': smearing with Fermi-Dirac function."""
        ),
    )

    sic_gamma: float = Field(0.0, description="Strength of the gammaDFT potential.")

    pol_type: Literal["none", "e", "h"] = Field(
        "none",
        description=dedent(
            """\
            Type of polaron in gammaDFT.
            - 'none': no polaron.
            - 'e': electron polaron.
            - 'h': hole polaron."""
        ),
    )

    sic_energy: bool = Field(
        False,
        description=dedent(
            """\
            Enable the calculation of the total energy in gammaDFT. When .true., a preliminary
            calculation is performed to calculate the electron density in the absence of the
            polaron. When .false., the total energy printed in output should not be considered. For
            structural relaxations, it is recommended to use .false. to avoid doubling the
            computational cost."""
        ),
    )

    sci_vb: Annotated[float, Quantity(units="eV", dimensionality="energy")] = Field(
        0.0,
        description=dedent(
            """\
            Valence band shift through self-consistent scissor operator. When performing gammaDFT
            calculations of polarons, the polaron level is not shifted."""
        ),
    )

    sci_cb: Annotated[float, Quantity(units="eV", dimensionality="energy")] = Field(
        0.0,
        description=dedent(
            """\
            Conduction band band shift through self-consistent scissor operator. When performing
            gammaDFT calculations of polarons, the polaron level is not shifted."""
        ),
    )

    ecfixed: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.0, description=""
    )

    qcutz: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.0, description=""
    )

    q2sigma: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.01,
        description=dedent(
            """\
            ecfixed, qcutz, q2sigma:  parameters for modified functional to be used in
            variable-cell molecular dynamics (or in stress calculation). 'ecfixed' is the value of
            the constant-cutoff; 'qcutz' and 'q2sigma' are the height and the width of the energy
            step for reciprocal vectors whose square modulus is greater than 'ecfixed'. In the
            kinetic energy, G^2 is replaced by G^2 + qcutz * (1 + erf ( (G^2 - ecfixed)/q2sigma) )
            See: M. Bernasconi et al, J. Phys. Chem. Solids 56, 501 (1995),
            doi:10.1016/0022-3697(94)00228-2 (https://doi.org/10.1016/0022-3697(94)00228-2)"""
        ),
    )

    input_dft: str | None = Field(
        None,
        json_schema_extra={
            "conditional_default": [{"when": None, "value": "from_pseudopotential"}],
        },
        description=dedent(
            """\
            Exchange-correlation functional: eg 'PBE', 'BLYP' etc See Modules/funct.f90 for allowed
            values. Overrides the value read from pseudopotential files. Use with care and if you
            know what you are doing!"""
        ),
    )

    ace: bool = Field(
        True,
        description=dedent(
            """\
            Use Adaptively Compressed Exchange operator as in Lin Lin, J. Chem. Theory Comput.
            2016, 12, 2242--2249, doi:10.1021/acs.jctc.6b00092
            (https://doi.org/10.1021/acs.jctc.6b00092)  Set to false to use standard Exchange (much
            slower)"""
        ),
    )

    exx_fraction: float | None = Field(
        None,
        json_schema_extra={"conditional_default": [{"when": None, "value": "internal"}]},
        description=dedent(
            """\
            Fraction of EXX for hybrid functional calculations. In the case of input_dft='PBE0',
            the default value is 0.25, while for input_dft='B3LYP' the exx_fraction default value
            is 0.20."""
        ),
    )

    screening_parameter: Annotated[float, Quantity(units="bohr^-1", dimensionality="length^-1")] = (
        Field(
            0.106,
            description=dedent(
                """\
                screening_parameter for HSE like hybrid functionals. For more information, see: J.
                Chem. Phys. 118, 8207 (2003), doi:10.1063/1.1564060
                (https://doi.org/10.1063/1.1564060) J. Chem. Phys. 124, 219906 (2006),
                doi:10.1063/1.2204597 (https://doi.org/10.1063/1.2204597)"""
            ),
        )
    )

    exxdiv_treatment: Literal["gygi-baldereschi", "vcut_spherical", "vcut_ws", "none"] = Field(
        "gygi-baldereschi",
        description=dedent(
            """\
            Specific for EXX. It selects the kind of approach to be used for treating the Coulomb
            potential divergencies at small q vectors.
            - 'gygi-baldereschi': appropriate for cubic and quasi-cubic supercells.
            - 'vcut_spherical': appropriate for cubic and quasi-cubic supercells (untested for
              non-orthogonal crystal axis).
            - 'vcut_ws': appropriate for strongly anisotropic supercells, see also ecutvcut
              (untested for non-orthogonal crystal axis).
            - 'none': sets Coulomb potential at G,q=0 to 0.0 (required for GAU-PBE)."""
        ),
    )

    exx_type: Literal["bands", "band_pairs"] = Field(
        "band_pairs",
        description=dedent(
            """\
            Specific for EXX. This keyword defines the band distribution scheme to use when band
            groups are enabled. When band groups are not used (-nb=1 or not specified), the two
            schemes are equivalent, but their internal implementations differ.
            - 'bands': distribute bands among band groups (GPU execution not yet implemented).
            - 'band_pairs': distribute band pairs among band groups (see Barnes et al., Computer
              Physics Communications, Volume 214, 2017, Pages 52-58)."""
        ),
    )

    x_gamma_extrapolation: bool = Field(
        True,
        description=dedent(
            """\
            Specific for EXX. If .true., extrapolate the G=0 term of the potential (see README in
            examples/EXX_example for more) Set this to .false. for GAU-PBE."""
        ),
    )

    ecutvcut: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.0,
        description=dedent(
            """\
            Reciprocal space cutoff for correcting Coulomb potential divergencies at small q
            vectors."""
        ),
    )

    nqx1: int | None = Field(
        None,
        json_schema_extra={"computed_default": True},
        description=dedent(
            """\
            Three-dimensional mesh for q (k1-k2) sampling of the Fock operator (EXX). Can be
            smaller than the number of k-points.  Currently this defaults to the size of the
            k-point mesh used. In QE =< 5.0.2 it defaulted to nqx1=nqx2=nqx3=1."""
        ),
    )

    nqx2: int | None = Field(
        None,
        json_schema_extra={"computed_default": True},
        description=dedent(
            """\
            Three-dimensional mesh for q (k1-k2) sampling of the Fock operator (EXX). Can be
            smaller than the number of k-points.  Currently this defaults to the size of the
            k-point mesh used. In QE =< 5.0.2 it defaulted to nqx1=nqx2=nqx3=1."""
        ),
    )

    nqx3: int | None = Field(
        None,
        json_schema_extra={"computed_default": True},
        description=dedent(
            """\
            Three-dimensional mesh for q (k1-k2) sampling of the Fock operator (EXX). Can be
            smaller than the number of k-points.  Currently this defaults to the size of the
            k-point mesh used. In QE =< 5.0.2 it defaulted to nqx1=nqx2=nqx3=1."""
        ),
    )

    localization_thr: float = Field(
        0.0,
        description=dedent(
            """\
            Overlap threshold over which the exchange integral over a pair of localized orbitals is
            included in the evaluation of EXX operator. Any value greater than 0.0 triggers the
            SCDM localization and the evaluation on EXX using the localized orbitals. Very small
            value of the threshold should yield the same result as the default EXX evaluation"""
        ),
    )

    dmft: bool = Field(
        False,
        description=dedent(
            """\
            If true, nscf calculation will exit in restart mode, scf calculation will restart from
            there if DMFT updates are provided as hdf5 archive. Scf calculation should be used only
            with electron_maxstep = 1. K_POINTS have to be identical and given explicitly with
            nosym."""
        ),
    )

    dmft_prefix: str | None = Field(
        None,
        json_schema_extra={"default_ref": "prefix"},
        description=dedent(
            """\
            prepended to hdf5 archive: dmft_prefix.h5  DMFT update should be provided in
            group/dataset as: - dft_misc_input/band_window with dimension [1, number of k-points, 2
            (real + complex)] - dft_update/delta_N with dimension [number of k-points, number of
            correlated orbitals, number of correlated orbitals, 2 (real + complex)]"""
        ),
    )

    ensemble_energies: bool = Field(
        False,
        description=dedent(
            """\
            If ensemble_energies = .true., an ensemble of xc energies is calculated
            non-selfconsistently for perturbed exchange-enhancement factors and LDA vs. PBE
            correlation ratios after each converged electronic ground state calculation.  Ensemble
            energies can be analyzed with the 'bee' utility included with libbeef.  Requires
            linking against libbeef. input_dft must be set to a BEEF-type functional (e.g.
            input_dft = 'BEEF-vdW')"""
        ),
    )

    edir: int = Field(
        1,
        description=dedent(
            """\
            The direction of the electric field or dipole correction is parallel to the bg(:,edir)
            reciprocal lattice vector, so the potential is constant in planes defined by FFT grid
            points; edir = 1, 2 or 3. Used only if tefield is .TRUE."""
        ),
    )

    emaxpos: float = Field(
        0.5,
        description=dedent(
            """\
            Position of the maximum of the saw-like potential along crystal axis edir, within the
            unit cell (see below), 0 < emaxpos < 1 Used only if tefield is .TRUE."""
        ),
    )

    eopreg: float = Field(
        0.1,
        description=dedent(
            """\
            Zone in the unit cell where the saw-like potential decreases. ( see below, 0 < eopreg <
            1 ). Used only if tefield is .TRUE."""
        ),
    )

    eamp: Annotated[
        float, Quantity(units="Ry e^-1 bohr^-1", dimensionality="energy charge^-1 length^-1")
    ] = Field(
        0.0,
        description=dedent(
            """\
            Amplitude of the electric field, in ***Hartree*** a.u.; 1 a.u. = 51.4220632*10^10 V/m.
            Used only if tefield==.TRUE. The saw-like potential increases with slope eamp in the
            region from (emaxpos+eopreg-1) to (emaxpos), then decreases to 0 until
            (emaxpos+eopreg), in units of the crystal vector edir. Important: the change of slope
            of this potential must be located in the empty region, or else unphysical forces will
            result."""
        ),
    )

    lforcet: bool = Field(
        False,
        description=dedent(
            """\
            When starting a non collinear calculation using an existing density file from a
            collinear lsda calculation assumes previous density points in z direction and rotates
            it in the direction described by angle1 and angle2 variables for atomic type 1"""
        ),
    )

    constrained_magnetization: Literal[
        "none", "total", "atomic", "total direction", "atomic direction"
    ] = Field(
        "none",
        description=dedent(
            """\
            Used to perform constrained calculations in magnetic systems. Currently available
            choices:  N.B.: symmetrization may prevent to reach the desired orientation of the
            magnetization. Try not to start with very highly symmetric configurations or use the
            nosym flag (only as a last remedy)
            - 'none': no constraint.
            - 'total': total magnetization is constrained by adding a penalty functional to the
              total energy:  LAMBDA * SUM_{i} ( magnetization(i) - fixed_magnetization(i) )**2
              where the sum over i runs over the three components of the magnetization. Lambda is a
              real number (see below). Noncolinear case only. Use tot_magnetization for LSDA.
            - 'atomic': atomic magnetization are constrained to the defined starting magnetization
              adding a penalty:  LAMBDA * SUM_{i,itype} ( magnetic_moment(i,itype) - mcons(i,itype)
              )**2  where i runs over the cartesian components (or just z in the collinear case)
              and itype over the types (1-ntype). mcons(:,:) array is defined from
              starting_magnetization, (also from angle1, angle2 in the noncollinear case). lambda
              is a real number.
            - 'total direction': the angle theta of the total magnetization with the z axis (theta
              = fixed_magnetization(3)) is constrained:  LAMBDA * (
              arccos(magnetization(3)/mag_tot) - theta )**2  where mag_tot is the modulus of the
              total magnetization.
            - 'atomic direction': not all the components of the atomic magnetic moment are
              constrained but only the cosine of angle1, and the penalty functional is:  LAMBDA *
              SUM_{itype} ( mag_mom(3,itype)/mag_mom_tot - cos(angle1(ityp)) )**2."""
        ),
    )

    Lambda: float = Field(
        1.0,
        description=dedent(
            """\
            parameter used for constrained_magnetization calculations N.B.: if the scf calculation
            does not converge, try to reduce lambda to obtain convergence, then restart the run
            with a larger lambda"""
        ),
    )

    report: int = Field(
        -1,
        description=dedent(
            """\
            determines when atomic magnetic moments are printed on output: report = 0  never report
            =-1  at the beginning of the scf and at convergence report = N  as -1, plus every N scf
            iterations"""
        ),
    )

    assume_isolated: Literal["none", "makov-payne", "martyna-tuckerman", "esm", "2D"] = Field(
        "none",
        description=dedent(
            """\
            Used to perform calculation assuming the system to be isolated (a molecule or a cluster
            in a 3D supercell).  Currently available choices:
            - 'none': regular periodic calculation w/o any correction.
            - 'makov-payne': the Makov-Payne correction to the total energy is computed. An
              estimate of the vacuum level is also calculated so that eigenvalues can be properly
              aligned. ONLY FOR CUBIC SYSTEMS (ibrav=1,2,3). Theory: G.Makov, and M.C.Payne,
              'Periodic boundary conditions in ab initio calculations' , PRB 51, 4014 (1995)
              (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.51.4014).
            - 'martyna-tuckerman': Martyna-Tuckerman correction to both total energy and scf
              potential. Adapted from: G.J. Martyna, and M.E. Tuckerman, 'A reciprocal space based
              method for treating long range interactions in ab-initio and force-field-based
              calculation in clusters', J. Chem. Phys. 110, 2810 (1999), doi:10.1063/1.477923
              (https://doi.org/10.1063/1.477923).
            - 'esm': Effective Screening Medium Method. For polarized or charged slab calculation,
              embeds the simulation cell within an effective semi- infinite medium in the
              perpendicular direction (along z). Embedding regions can be vacuum or semi-infinite
              metal electrodes (use esm_bc to choose boundary conditions). If between two
              electrodes, an optional electric field (esm_efield) may be applied. Method described
              in M. Otani and O. Sugino, 'First-principles calculations of charged surfaces and
              interfaces: A plane-wave nonrepeated slab approach', PRB 73, 115407 (2006)
              (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.73.115407).  NB: - Two
              dimensional (xy plane) average charge density and electrostatic potentials are
              printed out to 'prefix.esm1'.  - Requires cell with a_3 lattice vector along z,
              normal to the xy plane, with the slab centered around z=0.  - For bc2 with an
              electric field and bc3 boundary conditions, the inversion symmetry along z-direction
              is automatically eliminated.  - In case of calculation='vc-relax', use
              cell_dofree='2Dxy' or other parameters so that c-vector along z-axis should not be
              moved.  See esm_bc, esm_efield, esm_w, esm_nfit.
            - '2D': Truncation of the Coulomb interaction in the z direction for structures
              periodic in the x-y plane. Total energy, forces and stresses are computed in a
              two-dimensional framework. Linear-response calculations () done on top of a
              self-consistent calculation with this flag will automatically be performed in the
              2D framework as well. Please refer to: Sohier, T., Calandra, M., & Mauri, F.
              (2017), 'Density functional perturbation theory for gated two-dimensional
              heterostructures: Theoretical developments and application to flexural phonons in
              graphene', PRB, 96, 075448 (2017)
              (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.96.075448).  NB: - The
              length of the unit-cell along the z direction should be larger than twice the
              thickness of the 2D material (including electrons). A reasonable estimate for a
              layer's thickness could be the interlayer distance in the corresponding layered
              bulk material. Otherwise, the atomic thickness + 10 bohr should be a safe
              estimate. There is also a lower limit of 20 bohr imposed by the cutoff radius used
              to read pseudopotentials (see read_pseudo.f90 in Modules).  - As for ESM above,
              only in-plane stresses make sense and one should use cell_dofree= '2Dxy' in a
              vc-relax calculation."""
        ),
    )

    esm_bc: Literal["pbc", "bc1", "bc2", "bc3"] = Field(
        "pbc",
        description=dedent(
            """\
            If assume_isolated = 'esm', determines the boundary conditions used for either side of
            the slab.  Currently available choices:
            - 'pbc': regular periodic calculation (no ESM).
            - 'bc1': Vacuum-slab-vacuum (open boundary conditions).
            - 'bc2': Metal-slab-metal (dual electrode configuration). See also esm_efield.
            - 'bc3': Vacuum-slab-metal."""
        ),
    )

    esm_w: Annotated[float, Quantity(units="bohr", dimensionality="length")] = Field(
        0.0,
        description=dedent(
            """\
            If assume_isolated = 'esm', determines the position offset of the start of the
            effective screening region, measured relative to the cell edge. (ESM region begins at z
            = +/- [L_z/2 + esm_w] )."""
        ),
    )

    esm_efield: Annotated[
        float, Quantity(units="Ry e^-1 bohr^-1", dimensionality="energy charge^-1 length^-1")
    ] = Field(
        0.0,
        description=dedent(
            """\
            If assume_isolated = 'esm' and esm_bc = 'bc2', gives the magnitude of the electric
            field to be applied between semi-infinite ESM electrodes."""
        ),
    )

    esm_nfit: int = Field(
        4,
        description=dedent(
            """\
            If assume_isolated = 'esm', gives the number of z-grid points for the polynomial fit
            along the cell edge."""
        ),
    )

    lgcscf: bool = Field(
        False,
        description=dedent(
            """\
            If .TRUE. perform a constant bias potential (constant-mu) calculation with
            Grand-Canonical SCF. (JCP 146, 114104 (2017), R.Sundararaman, et al.)  NB: - The total
            energy displayed in output includes the potentiostat contribution (-mu*N). -
            assume_isolated = 'esm' and esm_bc = 'bc2' or 'bc3' must be set in SYSTEM namelist. -
            ESM-RISM is also supported (assume_isolated = 'esm' and esm_bc = 'bc1' and trism =
            .TRUE.). - mixing_mode has to be 'TF' or 'local-TF', also its default is 'TF.' - The
            default of mixing_beta is 0.1 with ESM-RISM, 0.2 without ESM-RISM. - The default of
            diago_thr_init is 1.D-5. - diago_full_acc is always .TRUE. . - diago_rmm_conv is always
            .TRUE. ."""
        ),
    )

    gcscf_mu: Annotated[float | None, Quantity(units="eV", dimensionality="energy")] = Field(
        None,
        description=dedent(
            """\
            The target Fermi energy of GC-SCF. One can start with appropriate total charge of the
            system by giving tot_charge ."""
        ),
    )

    gcscf_conv_thr: Annotated[float, Quantity(units="eV", dimensionality="energy")] = Field(
        0.01, description="Convergence threshold of Fermi energy for GC-SCF."
    )

    gcscf_beta: float = Field(
        0.05,
        description=dedent(
            """\
            Mixing factor for GC-SCF. Larger values are recommended, if systems with small DOS on
            Fermi surface as graphite."""
        ),
    )

    vdw_corr: Literal[
        "none", "grimme-d2", "grimme-d3", "tkatchenko-scheffler", "many-body-dispersion", "XDM"
    ] = Field(
        "none",
        description=dedent(
            """\
            Type of the van der Waals correction. Allowed values: Note that non-local functionals
            (eg vdw-DF) are NOT specified here but in input_dft
            - 'none': no van der Waals correction.
            - 'grimme-d2': Semiempirical Grimme's DFT-D2. Optional variables: london_s6,
              london_rcut, london_c6, london_rvdw S. Grimme, J. Comp. Chem. 27, 1787 (2006),
              doi:10.1002/jcc.20495 (https://doi.org/10.1002/jcc.20495) V. Barone et al., J. Comp.
              Chem. 30, 934 (2009), doi:10.1002/jcc.21112 (https://doi.org/10.1002/jcc.21112).
            - 'grimme-d3': Semiempirical Grimme's DFT-D3. Optional variables: dftd3_version,
              dftd3_threebody S. Grimme et al, J. Chem. Phys 132, 154104 (2010),
              doi:10.1063/1.3382344 (https://doi.org/10.1063/1.3382344).
            - 'tkatchenko-scheffler': Tkatchenko-Scheffler dispersion corrections with
              first-principle derived C6 coefficients. Optional variables: ts_vdw_econv_thr,
              ts_vdw_isolated See A. Tkatchenko and M. Scheffler, PRL 102, 073005 (2009)
              (https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.102.073005). J. Hermann et
              al., J. Chem. Phys. 159, 174802 (2023), doi:10.1063/5.0170972
              (https://doi.org/10.1063/5.0170972).
            - 'many-body-dispersion': Many-body dipersion (MBD) correction to long-range
              interactions. Optional variables: ts_vdw_isolated A. Ambrosetti et al., J. Chem.
              Phys. 140, 18A508 (2014), doi:10.1063/1.4865104 (https://doi.org/10.1063/1.4865104)
              J. Hermann et al., J. Chem. Phys. 159, 174802 (2023), doi:10.1063/5.0170972
              (https://doi.org/10.1063/5.0170972).
            - 'XDM': Exchange-hole dipole-moment model. Optional variables: xdm_a1, xdm_a2 A. D.
              Becke et al., J. Chem. Phys. 127, 154108 (2007), doi:10.1063/1.2795701
              (https://doi.org/10.1063/1.2795701) A. Otero de la Roza et al., J. Chem. Phys. 136,
              174109 (2012), doi:10.1063/1.4705760 (https://doi.org/10.1063/1.4705760)."""
        ),
    )

    london: bool = Field(False, description="")

    london_s6: float = Field(
        0.75, description="global scaling parameter for DFT-D. Default is good for PBE."
    )

    london_rcut: Annotated[float, Quantity(units="bohr", dimensionality="length")] = Field(
        200.0, description="cutoff radius for dispersion interactions"
    )

    dftd3_version: Literal[2, 3, 4, 5, 6] = Field(
        3,
        description=dedent(
            """\
            Version of Grimme implementation of Grimme-D3:  NOTE: not all functionals are
            parametrized.
            - '2': Original Grimme-D2 parametrization.
            - '3': Grimme-D3 (zero damping).
            - '4': Grimme-D3 (BJ damping).
            - '5': Grimme-D3M (zero damping).
            - '6': Grimme-D3M (BJ damping)."""
        ),
    )

    dftd3_threebody: bool = Field(
        True,
        description=dedent(
            """\
            Turn three-body terms in Grimme-D3 on. If .false. two-body contributions only are
            computed, using two-body parameters of Grimme-D3. If dftd3_version=2, three-body
            contribution is always disabled."""
        ),
    )

    ts_vdw_econv_thr: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        1e-06,
        description=dedent(
            """\
            Optional: controls the convergence of the vdW energy (and forces). The default value is
            a safe choice, likely too safe, but you do not gain much in increasing it"""
        ),
    )

    ts_vdw_isolated: bool = Field(
        False,
        description=dedent(
            """\
            Optional: set it to .TRUE. when computing the Tkatchenko-Scheffler vdW energy or the
            Many-Body dispersion (MBD) energy for an isolated (non-periodic) system."""
        ),
    )

    xdm: bool = Field(False, description="")

    xdm_a1: float | None = Field(
        None,
        json_schema_extra={"computed_default": True},
        description=dedent(
            """\
            Damping function parameter a1 (adimensional). It is NOT necessary to give a value if
            the functional is one of B86bPBE, PW86PBE, PBE, BLYP. For functionals in this list, the
            coefficients are given in:
            https://github.com/aoterodelaroza/postg/blob/master/xdm.param or
            https://erin-r-johnson.github.io/software/ A. Otero de la Roza, E. R. Johnson, J. Chem.
            Phys. 138, 204109 (2013), doi:10.1063/1.4705760 (https://doi.org/10.1063/1.4705760)"""
        ),
    )

    xdm_a2: Annotated[float | None, Quantity(units="angstrom", dimensionality="length")] = Field(
        None,
        json_schema_extra={"computed_default": True},
        description=dedent(
            """\
            Damping function parameter a2. It is NOT necessary to give a value if the functional is
            one of B86bPBE, PW86PBE, PBE, BLYP. For functionals in this list, the coefficients are
            given in: https://github.com/aoterodelaroza/postg/blob/master/xdm.param or
            https://erin-r-johnson.github.io/software/ A. Otero de la Roza, E. R. Johnson, J. Chem.
            Phys. 138, 204109 (2013), doi:10.1063/1.4705760 (https://doi.org/10.1063/1.4705760)"""
        ),
    )

    space_group: int = Field(
        0,
        description=dedent(
            """\
            The number of the space group of the crystal, as given in the International Tables of
            Crystallography A (ITA). This allows to give in input only the inequivalent atomic
            positions. The positions of all the symmetry equivalent atoms are calculated by the
            code. Used only when the atomic positions are of type crystal_sg. See also uniqueb,
            origin_choice, rhombohedral"""
        ),
    )

    uniqueb: bool = Field(
        False,
        description=dedent(
            """\
            Used only for monoclinic lattices. If .TRUE. the b unique ibrav (-12 or -13) are used,
            and symmetry equivalent positions are chosen assuming that the twofold axis or the
            mirror normal is parallel to the b axis. If .FALSE. it is parallel to the c axis."""
        ),
    )

    origin_choice: Literal[1, 2] = Field(
        1,
        description=dedent(
            """\
            Used only for space groups that in the ITA allow the use of two different origins.
            - '1': the first origin.
            - '2': the second origin."""
        ),
    )

    rhombohedral: bool = Field(
        True,
        description=dedent(
            """\
            Used only for rhombohedral space groups. When .TRUE. the coordinates of the
            inequivalent atoms are given with respect to the rhombohedral axes, when .FALSE. the
            coordinates of the inequivalent atoms are given with respect to the hexagonal axes.
            They are converted internally to the rhombohedral axes and ibrav=5 is used in both
            cases."""
        ),
    )

    zgate: float = Field(
        0.5,
        description=dedent(
            """\
            used only if gate = .TRUE. Specifies the position of the charged plate which represents
            the counter charge in doped systems (tot_charge .ne. 0). In units of the unit cell
            length in z direction, zgate in ]0,1[ Details of the gate potential can be found in T.
            Brumme, M. Calandra, F. Mauri; PRB 89, 245406 (2014)
            (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.89.245406)."""
        ),
    )

    relaxz: bool = Field(
        False,
        description=dedent(
            """\
            used only if gate = .TRUE. Allows the relaxation of the system towards the charged
            plate. Use carefully and utilize either a layer of fixed atoms or a potential barrier
            (block=.TRUE.) to avoid the atoms moving to the position of the plate or the dipole of
            the dipole correction (dipfield=.TRUE.)."""
        ),
    )

    block: bool = Field(
        False,
        description=dedent(
            """\
            used only if gate = .TRUE. Adds a potential barrier to the total potential seen by the
            electrons to mimic a dielectric in field effect configuration and/or to avoid electrons
            spilling into the vacuum region for electron doping. Potential barrier is from block_1
            to block_2 and has a height of block_height. If dipfield = .TRUE. then eopreg is used
            for a smooth increase and decrease of the potential barrier."""
        ),
    )

    block_1: float = Field(
        0.45,
        description=dedent(
            """\
            used only if gate = .TRUE. and block = .TRUE. lower beginning of the potential barrier,
            in units of the unit cell size along z, block_1 in ]0,1["""
        ),
    )

    block_2: float = Field(
        0.55,
        description=dedent(
            """\
            used only if gate = .TRUE. and block = .TRUE. upper beginning of the potential barrier,
            in units of the unit cell size along z, block_2 in ]0,1["""
        ),
    )

    block_height: float = Field(
        0.0,
        description=dedent(
            """\
            used only if gate = .TRUE. and block = .TRUE. Height of the potential barrier in
            Rydberg."""
        ),
    )

    nextffield: int = Field(
        0,
        description=dedent(
            """\
            Number of activated external ionic force fields. See Doc/ExternalForceFields.tex for
            further explanation and parameterizations"""
        ),
    )

    celldm: Annotated[
        tuple[float, float, float, float, float, float],
        Quantity(units="1:bohr", dimensionality="dimensionless, 1:length"),
    ] = Field(
        (0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        description=dedent(
            """\
            Crystallographic constants - see the ibrav variable. Specify either these OR
            A,B,C,cosAB,cosBC,cosAC NOT both. Only needed values (depending on 'ibrav') must be
            specified alat = celldm(1) is the lattice parameter 'a' If ibrav==0, only celldm(1) is
            used if present; cell vectors are read from card CELL_PARAMETERS"""
        ),
    )

    starting_charge: Annotated[list[float], Quantity(units="e", dimensionality="charge")] = Field(
        default_factory=list,
        description=dedent(
            """\
            starting charge on atomic type 'i', to create starting potential with startingpot =
            'atomic'. (start = 1, end = ntyp)"""
        ),
    )

    starting_magnetization: list[float] = Field(
        default_factory=list,
        description=dedent(
            """\
            Starting spin polarization on atomic type 'i' in a spin-polarized (LSDA or
            non-collinear/spin-orbit) calculation. The input values can have an absolute value
            greater than or equal to 1, which will be interpreted as the site's magnetic moment.
            Alternatively, the values can range between -1 and 1, which will be interpreted as the
            site magnetization per valence electron. For QE-v7.2 and older versions, only the
            second option is allowed.  If you expect a nonzero magnetization in your ground state,
            you MUST either specify a nonzero value for at least one atomic type, or constrain the
            magnetization using variable tot_magnetization for LSDA, constrained_magnetization for
            noncollinear/spin-orbit calculations. If you don't, you will get a nonmagnetic (zero
            magnetization) state. In order to perform LSDA calculations for an antiferromagnetic
            state, define two different atomic species corresponding to sublattices of the same
            atomic type.  NOTE 1: starting_magnetization is ignored in most BUT NOT ALL cases in
            non-scf calculations: it is safe to keep the same values for the scf and subsequent
            non-scf calculation.  NOTE 2: If you fix the magnetization with tot_magnetization, do
            not specify starting_magnetization.  NOTE 3: In the noncollinear/spin-orbit case,
            starting with zero starting_magnetization on all atoms imposes time reversal symmetry.
            The magnetization is never calculated and is set to zero (the internal variable domag
            is set to .FALSE.). (start = 1, end = ntyp)"""
        ),
    )

    Hubbard_beta: Annotated[list[float], Quantity(units="eV", dimensionality="energy")] = Field(
        default_factory=list,
        description=dedent(
            """\
            Hubbard_beta(i) is the perturbation (on atom i) used to compute J0 with the
            linear-response method of Cococcioni and de Gironcoli, PRB 71, 035105 (2005)
            (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.71.035105) (only for DFT+U or
            DFT+U+V). See also PRB 84, 115108 (2011)
            (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.84.115108). (start = 1, end =
            ntyp)"""
        ),
    )

    angle1: list[float] = Field(
        default_factory=list,
        description=dedent(
            """\
            The angle expressed in degrees between the initial magnetization and the z-axis. For
            noncollinear calculations only; index i runs over the atom types. (start = 1, end =
            ntyp)"""
        ),
    )

    angle2: list[float] = Field(
        default_factory=list,
        description=dedent(
            """\
            The angle expressed in degrees between the projection of the initial magnetization on
            x-y plane and the x-axis. For noncollinear calculations only. (start = 1, end = ntyp)"""
        ),
    )

    fixed_magnetization: tuple[float, float, float] = Field(
        (0.0, 0.0, 0.0),
        description=dedent(
            """\
            total magnetization vector (x,y,z components) to be kept fixed when
            constrained_magnetization=='total"""
        ),
    )

    london_c6: Annotated[
        list[float] | None, Quantity(units="Ry bohr^6", dimensionality="energy length^6")
    ] = Field(
        None,
        json_schema_extra={"conditional_default": [{"when": None, "value": "internal"}]},
        description=dedent(
            """\
            atomic C6 coefficient of each atom type  ( if not specified default values from S.
            Grimme, J. Comp. Chem. 27, 1787 (2006), doi:10.1002/jcc.20495
            (https://doi.org/10.1002/jcc.20495) are used; see file Modules/mm_dispersion.f90 )
            (start = 1, end = ntyp)"""
        ),
    )

    london_rvdw: Annotated[list[float] | None, Quantity(units="bohr", dimensionality="length")] = (
        Field(
            None,
            json_schema_extra={"conditional_default": [{"when": None, "value": "internal"}]},
            description=dedent(
                """\
                atomic vdw radii of each atom type  ( if not specified default values from S.
                Grimme, J. Comp. Chem. 27, 1787 (2006), doi:10.1002/jcc.20495
                (https://doi.org/10.1002/jcc.20495) are used; see file Modules/mm_dispersion.f90 )
                (start = 1, end = ntyp)"""
            ),
        )
    )
